name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - "README.md"
      - "**/*.md"
      - "docs/**"
  pull_request:
    branches: [ main ]
    paths-ignore:
      - "README.md"
      - "**/*.md"
      - "docs/**"
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        python-version: ['3.9']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install minimal dependencies for CI
      run: |
        python -m pip install --upgrade pip
        pip install pandas==2.2.2 numpy==1.26.4 scikit-learn==1.4.2 seaborn==0.13.2 matplotlib==3.8.4 flake8==7.1.1
    
    - name: Lint with flake8
      run: |
        flake8 src/ --count --select=E9,F63,F7,F82 --show-source --statistics || true
    
    - name: Smoke import check (no optional deps)
      env:
        MPLBACKEND: Agg
      run: |
        python - << 'PY'
        import pandas, numpy, sklearn, seaborn, matplotlib
        try:
            import xgboost
        except Exception as e:
            print("xgboost import warning:", e)
        try:
            import imblearn
        except Exception as e:
            print("imblearn import warning:", e)
        print("Smoke imports OK")
        PY

    # Skip notebook execution in CI to avoid flaky remote builds. Run locally when needed.

  # build-docs job removed (no Sphinx config in repo). Re-enable when docs are added.
